name: Check Branch Name

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^SIGLA-DO-PROJETO-[0-9]+-[a-zA-Z0-9-]+$ ]]; then
            echo "❌ O nome da branch deve seguir o padrão: SIGLA-DO-PROJETO-numeroDaTarefa-nomeDaTarefa"
            exit 1
          fi
